compile::stdout 0

compile::stderr 5
tests2/inputs/break_invalid_location.own:4:5:[1;31merror[0;39m:break statement outside of a for loop
     3 | fn main() i32 {
     4 |     break
       |     ^
     5 |     continue

compile::return_code 1

