compile::stdout 0

compile::stderr 35
tests2/inputs/function_callback_errors.own:9:5:[1;31merror[0;39m:1 arguments are passed to function `ptr`, but 2 arguments expected
     8 |     let ptr fn(i32, i32)i32 = add
     9 |     ptr(8)
       |     ^
    10 |     ptr(9, 10, 11)
tests2/inputs/function_callback_errors.own:8:13:[1;34mnote[0;39m:function `ptr` defined here
     7 | fn main() i32 {
     8 |     let ptr fn(i32, i32)i32 = add
       |             ^
     9 |     ptr(8)
tests2/inputs/function_callback_errors.own:10:5:[1;31merror[0;39m:3 arguments are passed to function `ptr`, but 2 arguments expected
     9 |     ptr(8)
    10 |     ptr(9, 10, 11)
       |     ^
    11 |     ptr(12.1, 13)
tests2/inputs/function_callback_errors.own:8:13:[1;34mnote[0;39m:function `ptr` defined here
     7 | fn main() i32 {
     8 |     let ptr fn(i32, i32)i32 = add
       |             ^
     9 |     ptr(8)
tests2/inputs/function_callback_errors.own:11:9:[1;31merror[0;39m:argument is of type `f32`, but the corresponding parameter is of type `i32`
    10 |     ptr(9, 10, 11)
    11 |     ptr(12.1, 13)
       |         ^
    12 | 
tests2/inputs/function_callback_errors.own:8:13:[1;34mnote[0;39m:function callback defined here
     7 | fn main() i32 {
     8 |     let ptr fn(i32, i32)i32 = add
       |             ^
     9 |     ptr(8)
tests2/inputs/function_callback_errors.own:13:17:[1;31merror[0;39m:type `i32` cannot be implicitly converted to `i16`
    12 | 
    13 |     let num i16 = ptr(12, 13)
       |                 ^
    14 | 

compile::return_code 1

