compile::stdout 0

compile::stderr 10
./tests2/inputs/function_pointer_instead_of_call.own:11:10:[1;31merror[0;39m:argument is of type `fn()i32`, but the corresponding parameter `num` is of type `i32`
    10 | fn main() i32 {
    11 |     take(one)
       |          ^
    12 |     return 0
./tests2/inputs/function_pointer_instead_of_call.own:7:9:[1;34mnote[0;39m:corresponding parameter `num` defined here
     6 | 
     7 | fn take(num i32) {
       |         ^
     8 | }

compile::return_code 1

